### ISSUE TITLE
bug: xlrelease::xlr_config_item_hash will create with each run a new jenkins entry in xl release

### ISSUE THREAD

**Issue by ltutar** [WianVos/puppet-xlrelease#8]
I have the following yaml:
xlrelease::xlr_config_item_hash:
  'jenkins':
    type: 'jenkins.Server'
    title: 'jenkins1'
    properties:
      title: "jenkins"
      username: "jenkins_user"
      password: "jenkins_user_password"
      url: 'http://192.168.234.44:8080/'

Each puppet run will create a new jenkins entry in xlrelease.

Notice: unable to reach localhost:5516
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: Finished catalog run in 52.59 seconds
[root@puppetagent7 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent7.home
Info: Applying configuration version '1433193476'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: Finished catalog run in 3.23 seconds
[root@puppetagent7 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent7.home
Info: Applying configuration version '1433193492'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: Finished catalog run in 4.32 seconds
[root@puppetagent7 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent7.home
Info: Applying configuration version '1433193651'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: Finished catalog run in 3.33 seconds
[root@puppetagent7 ~]#
![grabberraster 0853](https://cloud.githubusercontent.com/assets/7237078/7923625/0369cc72-08b5-11e5-9364-c0f34b11adb2.jpg)

**Comment by ltutar** [comment]
also for jenkins configuration from the example

Info: Caching catalog for puppetagent7.home
Info: Applying configuration version '1433194242'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git_test1]/ensure: created
Notice: Finished catalog run in 3.27 seconds
[root@puppetagent7 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent7.home
Info: Applying configuration version '1433197007'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git_test1]/ensure: created
Notice: Finished catalog run in 3.38 seconds

**Comment by WianVos** [comment]
fixed this by having the properties pruned for nil values and the properties hash sorted by keys..

**Comment by ltutar** [comment]
Still having an issue.

[root@puppetagent8 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent8.home
Info: Applying configuration version '1434314411'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git]/properties: properties changed '["title", "url"]' to '{"title"=>"git", "url"=>"ssh://vagrant@192.168.234.66/apps/git/repos/PetClinicDemo"}'
Notice: Finished catalog run in 4.16 seconds
[root@puppetagent8 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetagent8.home
Info: Applying configuration version '1434314437'
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[jenkins]/ensure: created
Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git]/properties: properties changed '["title", "url"]' to '{"title"=>"git", "url"=>"ssh://vagrant@192.168.234.66/apps/git/repos/PetClinicDemo"}'
Notice: Finished catalog run in 3.57 seconds
[root@puppetagent8 ~]# 

It will now do no restart anymore but it will still create or update.
![grabberraster 0861](https://cloud.githubusercontent.com/assets/7237078/8150362/e4da7e00-12e6-11e5-9065-4843fb26c436.jpg)

**Comment by WianVos** [comment]
This issue was moved to xebialabs/puppet-xlrelease#8
